// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwHFH57_8GkFYwVBm0oeijRrCHhnS6Us',
    appId: '1:938370323736:web:802663cc6cc763627a7a6d',
    messagingSenderId: '938370323736',
    projectId: 'ledger-626f4',
    authDomain: 'ledger-626f4.firebaseapp.com',
    storageBucket: 'ledger-626f4.firebasestorage.app',
    measurementId: 'G-7N5M7H3VLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdYGvQPt6z2RMrTiT07IrokS9SE4s4UY',
    appId: '1:938370323736:android:c48e475960be0d087a7a6d',
    messagingSenderId: '938370323736',
    projectId: 'ledger-626f4',
    storageBucket: 'ledger-626f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVcMnQ_0Z3iYc17fvWE60FhmvpjYELtQ',
    appId: '1:938370323736:ios:8a0805155418ec0f7a7a6d',
    messagingSenderId: '938370323736',
    projectId: 'ledger-626f4',
    storageBucket: 'ledger-626f4.firebasestorage.app',
    iosClientId: '938370323736-5ad281gd9kdpfluj27a22kvvjd7mogm4.apps.googleusercontent.com',
    iosBundleId: 'com.ningtoba.ledger.RunnerTests',
  );

}